<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageReference Include="PDFsharp-MigraDoc-GDI" Version="6.2.4" />
    <PackageReference Include="PDFsharp-MigraDoc-WPF" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublishingReviewContracts\PublishingReviewContracts.csproj" />
    <ProjectReference Include="..\PublishingReviewDataModels\PublishingReviewDataModels.csproj" />
  </ItemGroup>

</Project>
