using Microsoft.AspNetCore.Mvc;
using PublishingReviewApp.DTOs;
using PublishingReviewApp.Services;
namespace PublishingReviewApp.Controllers;
public class ReviewsController:Controller{private readonly ReviewService _reviews; private readonly ProductService _products; private readonly RatingService _ratings; private readonly PublishingReviewContracts.BusinessLogicContracts.IUserLogic _users; public ReviewsController(ReviewService r,ProductService p,RatingService rs,PublishingReviewContracts.BusinessLogicContracts.IUserLogic u){_reviews=r;_products=p;_ratings=rs;_users=u;}
int? CurrentUserId(){var email=HttpContext.Session.GetString("UserEmail"); if(string.IsNullOrWhiteSpace(email)) return null; return _users.ReadElement(new PublishingReviewContracts.SearchModels.UserSearchModel{Email=email})?.Id;}
public async Task<IActionResult> Index(string? q,int? rating,DateTime? from)=>View(await _reviews.List(q,rating,from));
public async Task<IActionResult> MyReviews(string? q,int? rating,DateTime? from){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); return View("Index",await _reviews.List(q,rating,from,uid));}
public async Task<IActionResult> Create(int productId){if(CurrentUserId()==null) return RedirectToAction("Enter","Home"); var p=await _products.Get(productId); if(p==null) return NotFound(); ViewBag.ProductName=p.Name; return View(new ReviewCreateDto{ProductId=productId});}
[HttpPost] public async Task<IActionResult> Create(ReviewCreateDto d){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); if(!ModelState.IsValid) return View(d); await _reviews.Create(d,uid.Value); await _ratings.SetRatingAsync(d.ProductId,uid.Value,d.RatingValue); TempData["Success"]="Отзыв добавлен"; return RedirectToAction(nameof(MyReviews));}
public async Task<IActionResult> Edit(int id){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); var d=await _reviews.GetForEdit(id,uid.Value); if(d==null) return Forbid(); return View(d);} [HttpPost] public async Task<IActionResult> Edit(ReviewCreateDto d){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); await _reviews.Update(d,uid.Value); TempData["Success"]="Отзыв обновлен"; return RedirectToAction(nameof(MyReviews));}
public async Task<IActionResult> Delete(int id){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); var d=await _reviews.GetForEdit(id,uid.Value); if(d==null) return Forbid(); return View(d);} [HttpPost,ActionName("Delete")] public async Task<IActionResult> DeleteConfirmed(int id){var uid=CurrentUserId(); if(uid==null) return RedirectToAction("Enter","Home"); await _reviews.Delete(id,uid.Value); TempData["Success"]="Отзыв удален"; return RedirectToAction(nameof(MyReviews));}}
