using Microsoft.EntityFrameworkCore;
using PublishingReviewApp.DTOs;
using PublishingReviewDatabase;
using PublishingReviewDatabaseImplements.Models.Shop;
namespace PublishingReviewApp.Services;
public class CategoryService{private readonly PublishingDatabase _db; public CategoryService(PublishingDatabase db)=>_db=db; public async Task<List<Category>> GetAll()=>await _db.Categories.OrderBy(x=>x.Name).ToListAsync();}
public class RatingService{private readonly PublishingDatabase _db; public RatingService(PublishingDatabase db)=>_db=db; public async Task SetRatingAsync(int productId,int userId,int value){if(value<1||value>5) throw new Exception("Оценка от 1 до 5"); var item=await _db.ProductRatings.FirstOrDefaultAsync(x=>x.ProductId==productId&&x.UserId==userId); if(item==null) _db.ProductRatings.Add(new ProductRating{ProductId=productId,UserId=userId,Value=value}); else {item.Value=value; item.CreatedAt=DateTime.UtcNow;} await _db.SaveChangesAsync();}}
public class ProductService{private readonly PublishingDatabase _db; public ProductService(PublishingDatabase db)=>_db=db;
public async Task<List<ProductDto>> Search(string? q,int? category,decimal? minP,decimal? maxP,double? minR){var query=_db.Products.Include(x=>x.ProductCategories).ThenInclude(pc=>pc.Category).Include(x=>x.Reviews).Include(x=>x.Ratings).AsQueryable(); if(!string.IsNullOrWhiteSpace(q))query=query.Where(x=>x.Name.ToLower().Contains(q.ToLower())); if(category.HasValue)query=query.Where(x=>x.ProductCategories.Any(pc=>pc.CategoryId==category)); if(minP.HasValue)query=query.Where(x=>x.Price>=minP); if(maxP.HasValue)query=query.Where(x=>x.Price<=maxP); var list=await query.ToListAsync(); var mapped=list.Select(Map).ToList(); if(minR.HasValue) mapped=mapped.Where(x=>x.AverageRating>=minR).ToList(); return mapped;}
public async Task<ProductDto?> Get(int id){var p=await _db.Products.Include(x=>x.ProductCategories).ThenInclude(pc=>pc.Category).Include(x=>x.Reviews).Include(x=>x.Ratings).FirstOrDefaultAsync(x=>x.Id==id); return p==null?null:Map(p);} public async Task Create(ProductCreateDto d){if(string.IsNullOrWhiteSpace(d.Name)||d.Price<=0) throw new Exception("Проверьте название и цену"); var p=new Product{Name=d.Name.Trim(),Description=d.Description?.Trim()??"",Price=d.Price,ImageUrl=d.ImageUrl}; _db.Products.Add(p); await _db.SaveChangesAsync(); foreach(var c in d.CategoryIds.Distinct()) _db.ProductCategories.Add(new ProductCategory{ProductId=p.Id,CategoryId=c}); await _db.SaveChangesAsync();}
public async Task Update(ProductCreateDto d){var p=await _db.Products.FirstOrDefaultAsync(x=>x.Id==d.Id)??throw new Exception("Товар не найден"); p.Name=d.Name.Trim(); p.Description=d.Description?.Trim()??""; p.Price=d.Price; p.ImageUrl=d.ImageUrl; var ex=_db.ProductCategories.Where(x=>x.ProductId==d.Id); _db.ProductCategories.RemoveRange(ex); await _db.SaveChangesAsync(); foreach(var c in d.CategoryIds.Distinct()) _db.ProductCategories.Add(new ProductCategory{ProductId=p.Id,CategoryId=c}); await _db.SaveChangesAsync();}
public async Task Delete(int id){var p=await _db.Products.FirstOrDefaultAsync(x=>x.Id==id); if(p!=null){_db.Products.Remove(p); await _db.SaveChangesAsync();}}
private static ProductDto Map(Product x)=>new(){Id=x.Id,Name=x.Name,Description=x.Description,Price=x.Price,CreatedAt=x.CreatedAt,ImageUrl=x.ImageUrl,CategoryIds=x.ProductCategories.Select(pc=>pc.CategoryId).ToList(),Categories=string.Join(", ",x.ProductCategories.Select(pc=>pc.Category.Name)),AverageRating=x.Ratings.Any()?Math.Round(x.Ratings.Average(r=>r.Value),2):0,ReviewsCount=x.Reviews.Count};}
public class ReviewService{private readonly PublishingDatabase _db; public ReviewService(PublishingDatabase db)=>_db=db;
public async Task<List<ReviewDto>> List(string? q,int? rating,DateTime? from,int? userId=null){var query=_db.ProductReviews.Include(x=>x.Product).Include(x=>x.User).AsQueryable(); if(userId.HasValue) query=query.Where(x=>x.UserId==userId); if(from.HasValue) query=query.Where(x=>x.CreatedAt.Date>=from.Value.Date); if(!string.IsNullOrWhiteSpace(q)) query=query.Where(x=>x.Text.ToLower().Contains(q.ToLower())||x.Product.Name.ToLower().Contains(q.ToLower())); var list=await query.OrderByDescending(x=>x.CreatedAt).ToListAsync(); var ids=list.Select(x=>new{x.ProductId,x.UserId}).ToList(); var ratings=await _db.ProductRatings.Where(r=>ids.Select(i=>i.ProductId).Contains(r.ProductId)&&ids.Select(i=>i.UserId).Contains(r.UserId)).ToListAsync(); var mapped=list.Select(x=>new ReviewDto{Id=x.Id,ProductId=x.ProductId,ProductName=x.Product.Name,UserId=x.UserId,UserName=x.User.FullName,Text=x.Text,CreatedAt=x.CreatedAt,UserRating=ratings.FirstOrDefault(r=>r.ProductId==x.ProductId&&r.UserId==x.UserId)?.Value}).ToList(); if(rating.HasValue)mapped=mapped.Where(x=>x.UserRating==rating).ToList(); return mapped;}
public async Task<ReviewCreateDto?> GetForEdit(int id,int userId){var r=await _db.ProductReviews.FirstOrDefaultAsync(x=>x.Id==id&&x.UserId==userId); return r==null?null:new ReviewCreateDto{Id=r.Id,ProductId=r.ProductId,Text=r.Text};}
public async Task Create(ReviewCreateDto d,int userId){if(string.IsNullOrWhiteSpace(d.Text)) throw new Exception("Пустой отзыв запрещён"); if(await _db.Products.AllAsync(x=>x.Id!=d.ProductId)) throw new Exception("Товар не найден"); _db.ProductReviews.Add(new ProductReview{ProductId=d.ProductId,UserId=userId,Text=d.Text.Trim()}); await _db.SaveChangesAsync();}
public async Task Update(ReviewCreateDto d,int userId){var r=await _db.ProductReviews.FirstOrDefaultAsync(x=>x.Id==d.Id)??throw new Exception("Отзыв не найден"); if(r.UserId!=userId) throw new Exception("Нельзя редактировать чужой отзыв"); r.Text=d.Text.Trim(); await _db.SaveChangesAsync();}
public async Task Delete(int id,int userId){var r=await _db.ProductReviews.FirstOrDefaultAsync(x=>x.Id==id)??throw new Exception("Отзыв не найден"); if(r.UserId!=userId) throw new Exception("Нельзя удалять чужой отзыв"); _db.ProductReviews.Remove(r); await _db.SaveChangesAsync();}}
